# Generated by Django 4.2 on 2024-12-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        db_column="nickname", help_text="nickname", max_length=50
                    ),
                ),
                (
                    "name",
                    models.CharField(db_column="name", help_text="name", max_length=50),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
