# Generated by Django 4.2 on 2025-01-13 20:36

from django.db import migrations, models

import backend.accounts.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "username",
                    models.CharField(
                        db_column="userid",
                        error_messages={"중복된 아이디 입니다."},
                        help_text="필수 입력 사항입니다. 150자 이하. 문자, 숫자 및 @/./+/-/_만 가능합니다.",
                        max_length=150,
                        unique=True,
                        validators=[backend.accounts.validators.UnicodeUsernameValidator()],
                    ),
                ),
                (
                    "nickname",
                    models.CharField(db_column="nickname", help_text="nickname", max_length=50),
                ),
                (
                    "name",
                    models.CharField(db_column="name", help_text="실제이름", max_length=50),
                ),
                ("postcode", models.CharField(max_length=10)),
                ("mainaddress", models.CharField(max_length=255)),
                ("subaddress", models.CharField(max_length=255)),
                (
                    "extraaddress",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("birth", models.DateField()),
                ("email", models.EmailField(max_length=30)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        default="static/images/default_profile.jpg",
                        upload_to="images/",
                    ),
                ),
                ("introduce", models.TextField(blank=True, max_length=255, null=True)),
                ("total_score", models.FloatField(default=30)),
                (
                    "followings",
                    models.ManyToManyField(blank=True, related_name="followers", to="backend_accounts.user"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
