# Generated by Django 4.2 on 2025-01-22 17:05

from django.db import migrations, models

import backend.accounts.validators


class Migration(migrations.Migration):

    dependencies = [
        ("backend_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birth",
            field=models.DateField(help_text="사용자의 생년월일"),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, help_text="사용자 계정 생성 시간"),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(help_text="사용자의 이메일 주소", max_length=254),
        ),
        migrations.AlterField(
            model_name="user",
            name="extraaddress",
            field=models.CharField(
                blank=True,
                help_text="사용자의 추가 주소 (선택 입력)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="followings",
            field=models.ManyToManyField(
                blank=True,
                help_text="사용자가 팔로우한 사용자 목록",
                related_name="followers",
                to="backend_accounts.user",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="static/images/default_profile.jpg",
                help_text="사용자 프로필 이미지",
                upload_to="images/",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="introduce",
            field=models.TextField(
                blank=True,
                help_text="사용자 자기소개 (선택 입력)",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="mainaddress",
            field=models.CharField(help_text="사용자의 기본 주소", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(db_column="name", help_text="사용자의 실제 이름", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="nickname",
            field=models.CharField(db_column="nickname", help_text="사용자의 별명", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="postcode",
            field=models.CharField(help_text="우편번호", max_length=10),
        ),
        migrations.AlterField(
            model_name="user",
            name="subaddress",
            field=models.CharField(help_text="사용자의 상세 주소", max_length=255),
        ),
        migrations.AlterField(
            model_name="user",
            name="total_score",
            field=models.FloatField(default=30, help_text="사용자의 초기 매너 점수"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                db_column="userid",
                error_messages={"unique": "중복된 아이디입니다."},
                help_text="필수 입력 사항입니다. 150자 이하. 문자, 숫자 및 @/./+/-/_만 가능합니다.",
                max_length=150,
                unique=True,
                validators=[backend.accounts.validators.UnicodeUsernameValidator()],
            ),
        ),
    ]
